# Site settings
title: Buldogchef's Blog
email: maros.kukan@me.com
description: Awesome blog about engineering, programming, life and challenges they bring.
baseurl: ""
url: "https://buldogchef.com"

twitter_username: jekyllrb
github_username:  jekyll

permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: buldogchef

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

